UPDATE faculty_time_table.specialisation SET code = 100, credits_required = 120, description = 'Study of computer systems', name = 'Computer Science', year = 2023 WHERE specialisationid = 1;
UPDATE faculty_time_table.specialisation SET code = 200, credits_required = 100, description = 'Focus on database technologies', name = 'Database Management', year = 2023 WHERE specialisationid = 2;
UPDATE faculty_time_table.specialisation SET code = 300, credits_required = 110, description = 'Exploring AI concepts', name = 'Artificial Intelligence', year = 2023 WHERE specialisationid = 3;
UPDATE faculty_time_table.specialisation SET code = 101, credits_required = 90, description = 'Creating dynamic websites', name = 'Web Development', year = 2023 WHERE specialisationid = 4;
UPDATE faculty_time_table.specialisation SET code = 201, credits_required = 95, description = 'Analyzing and interpreting data', name = 'Data Analysis', year = 2023 WHERE specialisationid = 5;
UPDATE faculty_time_table.specialisation SET code = 301, credits_required = 105, description = 'Designing and building software systems', name = 'Software Engineering', year = 2023 WHERE specialisationid = 6;
UPDATE faculty_time_table.specialisation SET code = 102, credits_required = 80, description = 'Securing computer networks', name = 'Network Security', year = 2023 WHERE specialisationid = 7;
UPDATE faculty_time_table.specialisation SET code = 202, credits_required = 85, description = 'Creating visual content', name = 'Computer Graphics', year = 2023 WHERE specialisationid = 8;
UPDATE faculty_time_table.specialisation SET code = 302, credits_required = 115, description = 'Advanced AI concepts', name = 'Machine Learning', year = 2023 WHERE specialisationid = 9;
UPDATE faculty_time_table.specialisation SET code = 103, credits_required = 75, description = 'Managing and leading projects', name = 'Project Management', year = 2023 WHERE specialisationid = 10;
UPDATE faculty_time_table.specialisation SET code = 104, credits_required = 80, description = 'Introduction to Machine Learning', name = 'Machine Learning Basics', year = 2023 WHERE specialisationid = 11;
UPDATE faculty_time_table.specialisation SET code = 204, credits_required = 110, description = 'Database Administration', name = 'Advanced Database Management', year = 2023 WHERE specialisationid = 12;
UPDATE faculty_time_table.specialisation SET code = 304, credits_required = 105, description = 'Computer Vision', name = 'Advanced Computer Graphics', year = 2023 WHERE specialisationid = 13;
UPDATE faculty_time_table.specialisation SET code = 105, credits_required = 75, description = 'Human-Computer Interaction', name = 'Interactive Design', year = 2023 WHERE specialisationid = 14;
UPDATE faculty_time_table.specialisation SET code = 205, credits_required = 85, description = 'Statistical Analysis', name = 'Advanced Data Analysis', year = 2023 WHERE specialisationid = 15;
UPDATE faculty_time_table.specialisation SET code = 305, credits_required = 95, description = 'Robotics', name = 'Advanced Robotics', year = 2023 WHERE specialisationid = 16;
UPDATE faculty_time_table.specialisation SET code = 106, credits_required = 70, description = 'Data Structures and Algorithms', name = 'Algorithmic Design', year = 2023 WHERE specialisationid = 17;
UPDATE faculty_time_table.specialisation SET code = 206, credits_required = 80, description = 'Information Security', name = 'Advanced Network Security', year = 2023 WHERE specialisationid = 18;
UPDATE faculty_time_table.specialisation SET code = 306, credits_required = 105, description = 'Game Development', name = 'Advanced Game Programming', year = 2023 WHERE specialisationid = 19;
UPDATE faculty_time_table.specialisation SET code = 107, credits_required = 90, description = 'Software Testing and Quality Assurance', name = 'Quality Assurance', year = 2023 WHERE specialisationid = 20;
